

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app  # Mount the project directory for development
    depends_on:
      - postgres
    networks:
      - webnet

  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - webnet

volumes:
  postgres_data:

networks:
  webnet: 