"""Initial migration based on corrected models

Revision ID: 22cbc82e4993
Revises: 
Create Date: 2025-04-30 10:51:21.259118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22cbc82e4993'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yandex_login', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_yandex_login'), ['yandex_login'], unique=True)

    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('metrika_goals', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_user_id'), ['user_id'], unique=False)

    op.create_table('yandex_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'login', name='_client_login_uc')
    )
    with op.batch_alter_table('yandex_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_yandex_account_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_yandex_account_login'), ['login'], unique=False)

    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yandex_account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_access_token', sa.LargeBinary(), nullable=False),
    sa.Column('encrypted_refresh_token', sa.LargeBinary(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['yandex_account_id'], ['yandex_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('yandex_account_id')
    )
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_user_id'), ['user_id'], unique=False)

    op.create_table('weekly_campaign_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('yandex_account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('campaign_name', sa.String(), nullable=True),
    sa.Column('campaign_type', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['yandex_account_id'], ['yandex_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('yandex_account_id', 'campaign_id', 'week_start_date', name='uq_weekly_campaign_stat')
    )
    with op.batch_alter_table('weekly_campaign_stat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_campaign_stat_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_campaign_stat_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_campaign_stat_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_campaign_stat_week_start_date'), ['week_start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_campaign_stat_yandex_account_id'), ['yandex_account_id'], unique=False)

    op.create_table('daily_campaign_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yandex_account_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('weekly_campaign_stat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['weekly_campaign_stat_id'], ['weekly_campaign_stat.id'], ),
    sa.ForeignKeyConstraint(['yandex_account_id'], ['yandex_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('yandex_account_id', 'date', 'campaign_id', name='uq_daily_campaign_stat')
    )
    with op.batch_alter_table('daily_campaign_stat', schema=None) as batch_op:
        batch_op.create_index('idx_daily_client_camp_date', ['date', 'campaign_id', 'yandex_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_campaign_stat_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_campaign_stat_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_campaign_stat_weekly_campaign_stat_id'), ['weekly_campaign_stat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_campaign_stat_yandex_account_id'), ['yandex_account_id'], unique=False)

    op.create_table('weekly_demographic_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('age_group', sa.String(length=20), nullable=False),
    sa.Column('yandex_account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('weekly_campaign_stat_id', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['weekly_campaign_stat_id'], ['weekly_campaign_stat.id'], ),
    sa.ForeignKeyConstraint(['yandex_account_id'], ['yandex_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start_date', 'campaign_id', 'gender', 'age_group', 'yandex_account_id', name='_week_demographic_uc')
    )
    with op.batch_alter_table('weekly_demographic_stat', schema=None) as batch_op:
        batch_op.create_index('idx_demogr_client_camp_week', ['client_id', 'campaign_id', 'week_start_date'], unique=False)
        batch_op.create_index('idx_demogr_user_camp_week', ['user_id', 'campaign_id', 'week_start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_demographic_stat_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_demographic_stat_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_demographic_stat_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_demographic_stat_week_start_date'), ['week_start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_demographic_stat_weekly_campaign_stat_id'), ['weekly_campaign_stat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_demographic_stat_yandex_account_id'), ['yandex_account_id'], unique=False)

    op.create_table('weekly_device_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('yandex_account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('weekly_campaign_stat_id', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['weekly_campaign_stat_id'], ['weekly_campaign_stat.id'], ),
    sa.ForeignKeyConstraint(['yandex_account_id'], ['yandex_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start_date', 'campaign_id', 'device_type', 'yandex_account_id', name='_week_device_uc')
    )
    with op.batch_alter_table('weekly_device_stat', schema=None) as batch_op:
        batch_op.create_index('idx_device_client_camp_week', ['client_id', 'campaign_id', 'week_start_date'], unique=False)
        batch_op.create_index('idx_device_user_camp_week', ['user_id', 'campaign_id', 'week_start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_device_stat_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_device_stat_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_device_stat_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_device_stat_week_start_date'), ['week_start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_device_stat_weekly_campaign_stat_id'), ['weekly_campaign_stat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_device_stat_yandex_account_id'), ['yandex_account_id'], unique=False)

    op.create_table('weekly_geo_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('yandex_account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('weekly_campaign_stat_id', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['weekly_campaign_stat_id'], ['weekly_campaign_stat.id'], ),
    sa.ForeignKeyConstraint(['yandex_account_id'], ['yandex_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start_date', 'campaign_id', 'location_id', 'yandex_account_id', name='_week_geo_uc')
    )
    with op.batch_alter_table('weekly_geo_stat', schema=None) as batch_op:
        batch_op.create_index('idx_geo_client_camp_week', ['client_id', 'campaign_id', 'week_start_date'], unique=False)
        batch_op.create_index('idx_geo_user_camp_week', ['user_id', 'campaign_id', 'week_start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_geo_stat_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_geo_stat_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_geo_stat_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_geo_stat_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_geo_stat_week_start_date'), ['week_start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_geo_stat_weekly_campaign_stat_id'), ['weekly_campaign_stat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_geo_stat_yandex_account_id'), ['yandex_account_id'], unique=False)

    op.create_table('weekly_placement_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('yandex_account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('weekly_campaign_stat_id', sa.Integer(), nullable=True),
    sa.Column('placement', sa.String(length=512), nullable=True),
    sa.Column('ad_network_type', sa.String(length=50), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['weekly_campaign_stat_id'], ['weekly_campaign_stat.id'], ),
    sa.ForeignKeyConstraint(['yandex_account_id'], ['yandex_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start_date', 'campaign_id', 'yandex_account_id', 'placement', 'ad_network_type', name='_week_placement_uc')
    )
    with op.batch_alter_table('weekly_placement_stat', schema=None) as batch_op:
        batch_op.create_index('idx_placement_client_camp_week', ['client_id', 'campaign_id', 'week_start_date'], unique=False)
        batch_op.create_index('idx_placement_user_camp_week', ['user_id', 'campaign_id', 'week_start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_placement_stat_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_placement_stat_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_placement_stat_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_placement_stat_week_start_date'), ['week_start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_placement_stat_weekly_campaign_stat_id'), ['weekly_campaign_stat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_placement_stat_yandex_account_id'), ['yandex_account_id'], unique=False)

    op.create_table('weekly_search_query_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('ad_group_id', sa.BigInteger(), nullable=False),
    sa.Column('yandex_account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('weekly_campaign_stat_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(length=1024), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['weekly_campaign_stat_id'], ['weekly_campaign_stat.id'], ),
    sa.ForeignKeyConstraint(['yandex_account_id'], ['yandex_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start_date', 'campaign_id', 'ad_group_id', 'yandex_account_id', 'query', name='_week_query_uc')
    )
    with op.batch_alter_table('weekly_search_query_stat', schema=None) as batch_op:
        batch_op.create_index('idx_query_client_camp_week', ['client_id', 'campaign_id', 'week_start_date'], unique=False)
        batch_op.create_index('idx_query_user_camp_week', ['user_id', 'campaign_id', 'week_start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_search_query_stat_ad_group_id'), ['ad_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_search_query_stat_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_search_query_stat_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_search_query_stat_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_search_query_stat_week_start_date'), ['week_start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_search_query_stat_weekly_campaign_stat_id'), ['weekly_campaign_stat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_search_query_stat_yandex_account_id'), ['yandex_account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_search_query_stat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_search_query_stat_yandex_account_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_search_query_stat_weekly_campaign_stat_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_search_query_stat_week_start_date'))
        batch_op.drop_index(batch_op.f('ix_weekly_search_query_stat_user_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_search_query_stat_client_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_search_query_stat_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_search_query_stat_ad_group_id'))
        batch_op.drop_index('idx_query_user_camp_week')
        batch_op.drop_index('idx_query_client_camp_week')

    op.drop_table('weekly_search_query_stat')
    with op.batch_alter_table('weekly_placement_stat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_placement_stat_yandex_account_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_placement_stat_weekly_campaign_stat_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_placement_stat_week_start_date'))
        batch_op.drop_index(batch_op.f('ix_weekly_placement_stat_user_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_placement_stat_client_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_placement_stat_campaign_id'))
        batch_op.drop_index('idx_placement_user_camp_week')
        batch_op.drop_index('idx_placement_client_camp_week')

    op.drop_table('weekly_placement_stat')
    with op.batch_alter_table('weekly_geo_stat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_geo_stat_yandex_account_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_geo_stat_weekly_campaign_stat_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_geo_stat_week_start_date'))
        batch_op.drop_index(batch_op.f('ix_weekly_geo_stat_user_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_geo_stat_location_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_geo_stat_client_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_geo_stat_campaign_id'))
        batch_op.drop_index('idx_geo_user_camp_week')
        batch_op.drop_index('idx_geo_client_camp_week')

    op.drop_table('weekly_geo_stat')
    with op.batch_alter_table('weekly_device_stat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_device_stat_yandex_account_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_device_stat_weekly_campaign_stat_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_device_stat_week_start_date'))
        batch_op.drop_index(batch_op.f('ix_weekly_device_stat_user_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_device_stat_client_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_device_stat_campaign_id'))
        batch_op.drop_index('idx_device_user_camp_week')
        batch_op.drop_index('idx_device_client_camp_week')

    op.drop_table('weekly_device_stat')
    with op.batch_alter_table('weekly_demographic_stat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_demographic_stat_yandex_account_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_demographic_stat_weekly_campaign_stat_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_demographic_stat_week_start_date'))
        batch_op.drop_index(batch_op.f('ix_weekly_demographic_stat_user_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_demographic_stat_client_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_demographic_stat_campaign_id'))
        batch_op.drop_index('idx_demogr_user_camp_week')
        batch_op.drop_index('idx_demogr_client_camp_week')

    op.drop_table('weekly_demographic_stat')
    with op.batch_alter_table('daily_campaign_stat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_campaign_stat_yandex_account_id'))
        batch_op.drop_index(batch_op.f('ix_daily_campaign_stat_weekly_campaign_stat_id'))
        batch_op.drop_index(batch_op.f('ix_daily_campaign_stat_date'))
        batch_op.drop_index(batch_op.f('ix_daily_campaign_stat_campaign_id'))
        batch_op.drop_index('idx_daily_client_camp_date')

    op.drop_table('daily_campaign_stat')
    with op.batch_alter_table('weekly_campaign_stat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_campaign_stat_yandex_account_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_campaign_stat_week_start_date'))
        batch_op.drop_index(batch_op.f('ix_weekly_campaign_stat_user_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_campaign_stat_client_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_campaign_stat_campaign_id'))

    op.drop_table('weekly_campaign_stat')
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_user_id'))

    op.drop_table('token')
    with op.batch_alter_table('yandex_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yandex_account_login'))
        batch_op.drop_index(batch_op.f('ix_yandex_account_client_id'))

    op.drop_table('yandex_account')
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_user_id'))

    op.drop_table('client')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_yandex_login'))

    op.drop_table('user')
    # ### end Alembic commands ###
