"""Add user_id, client_id, conversions to geo, device, demographic stats

Revision ID: a31b83509742
Revises: a51cc16ede2c
Create Date: 2025-04-29 05:03:55.127055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31b83509742'
down_revision = 'a51cc16ede2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_demographic_stat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('conversions', sa.Integer(), nullable=True))
        batch_op.drop_index('idx_demographic_user_camp_week')
        batch_op.drop_constraint('_week_demographic_uc', type_='unique')
        batch_op.create_unique_constraint('_week_demographic_uc', ['week_start_date', 'campaign_id', 'gender', 'age_group', 'yandex_account_id'])
        batch_op.create_index('idx_demogr_client_camp_week', ['client_id', 'campaign_id', 'week_start_date'], unique=False)
        batch_op.create_index('idx_demogr_user_camp_week', ['user_id', 'campaign_id', 'week_start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_demographic_stat_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_demographic_stat_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('weekly_device_stat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('conversions', sa.Integer(), nullable=True))
        batch_op.drop_constraint('_week_device_uc', type_='unique')
        batch_op.create_unique_constraint('_week_device_uc', ['week_start_date', 'campaign_id', 'device_type', 'yandex_account_id'])
        batch_op.drop_index('idx_device_user_camp_week')
        batch_op.create_index('idx_device_user_camp_week', ['user_id', 'campaign_id', 'week_start_date'], unique=False)
        batch_op.create_index('idx_device_client_camp_week', ['client_id', 'campaign_id', 'week_start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_device_stat_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_device_stat_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])

    with op.batch_alter_table('weekly_geo_stat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('conversions', sa.Integer(), nullable=True))
        batch_op.drop_constraint('_week_geo_uc', type_='unique')
        batch_op.create_unique_constraint('_week_geo_uc', ['week_start_date', 'campaign_id', 'location_id', 'yandex_account_id'])
        batch_op.drop_index('idx_geo_user_camp_week')
        batch_op.create_index('idx_geo_user_camp_week', ['user_id', 'campaign_id', 'week_start_date'], unique=False)
        batch_op.create_index('idx_geo_client_camp_week', ['client_id', 'campaign_id', 'week_start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_geo_stat_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_geo_stat_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_geo_stat', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_weekly_geo_stat_user_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_geo_stat_client_id'))
        batch_op.drop_index('idx_geo_client_camp_week')
        batch_op.drop_index('idx_geo_user_camp_week')
        batch_op.create_index('idx_geo_user_camp_week', ['yandex_account_id', 'campaign_id', 'week_start_date'], unique=False)
        batch_op.drop_constraint('_week_geo_uc', type_='unique')
        batch_op.create_unique_constraint('_week_geo_uc', ['week_start_date', 'campaign_id', 'location_id'])
        batch_op.drop_column('conversions')
        batch_op.drop_column('client_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('weekly_device_stat', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_weekly_device_stat_user_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_device_stat_client_id'))
        batch_op.drop_index('idx_device_client_camp_week')
        batch_op.drop_index('idx_device_user_camp_week')
        batch_op.create_index('idx_device_user_camp_week', ['yandex_account_id', 'campaign_id', 'week_start_date'], unique=False)
        batch_op.drop_constraint('_week_device_uc', type_='unique')
        batch_op.create_unique_constraint('_week_device_uc', ['week_start_date', 'campaign_id', 'device_type'])
        batch_op.drop_column('conversions')
        batch_op.drop_column('client_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('weekly_demographic_stat', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_weekly_demographic_stat_user_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_demographic_stat_client_id'))
        batch_op.drop_index('idx_demogr_user_camp_week')
        batch_op.drop_index('idx_demogr_client_camp_week')
        batch_op.drop_constraint('_week_demographic_uc', type_='unique')
        batch_op.create_unique_constraint('_week_demographic_uc', ['week_start_date', 'campaign_id', 'gender', 'age_group'])
        batch_op.create_index('idx_demographic_user_camp_week', ['yandex_account_id', 'campaign_id', 'week_start_date'], unique=False)
        batch_op.drop_column('conversions')
        batch_op.drop_column('client_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
